import type { Metadata } from 'next';
import { Nanum_Pen_Script } from 'next/font/google';
import './globals.css';
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  RedirectToSignIn,
} from '@clerk/nextjs';
import NavBar from './ui/navigation';

const nanum = Nanum_Pen_Script({
  weight: '400',
  subsets: ['latin'],
  style: 'normal',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang='en' className='inter.className'>
        <head>
          <link
            rel='apple-touch-icon'
            sizes='180x180'
            href='/apple-touch-icon.png'
          />
          <link
            rel='icon'
            type='image/png'
            sizes='32x32'
            href='/favicon-32x32.png'
          />
          <link
            rel='icon'
            type='image/png'
            sizes='16x16'
            href='/favicon-16x16.png'
          />
          <link rel='manifest' href='/site.webmanifest' />
        </head>
        <body className={`${nanum.className} flex h-screen w-screen`}>
          <SignedIn>
            <main className='flex h-screen w-screen flex-col flex-wrap bg-light-yellow text-oxford-blue'>
              <NavBar />
              <div className='overflow-auto pb-8 pt-36'>{children}</div>
            </main>
          </SignedIn>
          <SignedOut>
            <RedirectToSignIn />
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}
